version: '2.1'

services:
  item:
    build: microservices/item-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  warehouse:
    build: microservices/warehouse-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  storage:
    build: microservices/storage-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  compose:
    build: microservices/compose-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
