server.port: 7001

spring.data.mongodb:
  host: localhost
  port: 27017
  database: item-db

logging:
  level:
    root: INFO
    org.kusza.microserices: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080
spring.data.mongodb.host: mongodb

